configs: npcm: fix CONFIG_BOARD_INIT for the Nuvoton boards
Enable CONFIG_BOARD_INIT for arbel_evb, whose board_init() configures
the GFX pixel clock and was silently never called.  Disable it for the
three Poleg defconfigs that were missed by commit 70a4d1fa1ddb
("treewide: Remove empty board_init() function from all boards") and
now fail to link with "undefined reference to `board_init'".

Signed-off-by: Jim Liu <JJLIU0@nuvoton.com>